name: My First WorkFlow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
     - name: Print Greeting
       run: |
           echo "Hellow World"
           echo "Sachin Kulkarni!"
     - name: Print Good Bye
       run: echo "Done - Bye!"
